name: Deploy React application
on: [push, workflow_dispatch]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Where we are
        run: pwd
      - name: Checkout code
        uses: actions/checkout@v3
      - name: What we got
        run: ls -al
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."

