name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Welcome to the first Workflow"
      - name: Print goodbye
        run: echo "All done! bye"
